services:  # Port 8080 for web interface
  filebrowser:
    image: hurlenko/filebrowser
    user: "${DOCKER_UID}:${DOCKER_GID}"
    container_name: filebrowser
    volumes:
      - ${SHARE_PATH}:/data
      - ${PROJECT_PATH}/${CONFIG}/filebrowser:/config
    environment:
      - FB_NOAUTH=true  # Use caddy for authentication
    #  - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - proxy-net