include:
  - containers/caddy/compose.yml
  - containers/pihole/compose.yml
  - containers/wg-easy/compose.yml
  - containers/unbound/compose.yml

networks:
  caddy-net:
    driver: bridge
    ipam:
      config:
        - subnet: "${CADDY_NET_SUBNET}"
  unbound-net:
    driver: bridge