include:
  - containers/caddy/compose.yml
  - containers/pihole/compose.yml
  - containers/wg-easy/compose.yml
  - containers/unbound/compose.yml
  - containers/homeassistant/compose.yml

networks:
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: "${PROXY_NET_SUBNET}"
  private-net:
    driver: bridge
    ipam:
      config:
        - subnet: "${PRIVATE_NET_SUBNET}"