services:
  backrest:  # Port 9898
    image: garethgeorge/backrest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/backrest/data:/data
      - ${PROJECT_PATH}/${CONFIG}/backrest/config:/config
      - ${PROJECT_PATH}/${CONFIG}/backrest/cache:/cache
      - ${PROJECT_PATH}/${CONFIG}:/userdata/homelab-config # [optional] mount local paths to backup here.
      # - ${PROJECT_PATH}/${CONFIG}:/userdata  # For other data to be backed up
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=${TZ} # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    networks:
      - proxy-net