services:

  sqldb:
    image: mysql:8.3
    volumes:
      - "${PROJECT_PATH}/${CONFIG}/kimai/mysql:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${KIMAI_DATABASE_NAME}
      - MYSQL_USER=${KIMAI_DATABASE_USER}
      - MYSQL_PASSWORD=${KIMAI_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${KIMAI_DATABASE_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    networks:
      - private-net
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - "${PROJECT_PATH}/${CONFIG}/kimai/data:/opt/kimai/var/data"
      - "${PROJECT_PATH}/${CONFIG}/kimai/plugins:/opt/kimai/var/plugins"
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=${KIMAI_ADMIN_EMAIL}
      - ADMINPASS=${KIMAI_ADMIN_PASSWORD}
      - "DATABASE_URL=mysql://${KIMAI_DATABASE_USER}:${KIMAI_DATABASE_PASSWORD}@sqldb/${KIMAI_DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3.0"
    networks:
      - proxy-net
      - private-net
    depends_on:
      - sqldb
    restart: unless-stopped