services:
    iSponsorBlockTV:
        image: ghcr.io/dmunozv04/isponsorblocktv
        container_name: iSponsorBlockTV
        restart: unless-stopped
        volumes:
        - ${PROJECT_PATH}/${CONFIG}/isponsorblocktv:/app/data