services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "" # Auth by Caddy
      PIHOLE_DNS_: unbound
      CUSTOM_CACHE_SIZE: "0"  # Allow unbound to handle
      DNSMASQ_LISTENING: "all"  # Allow VPN access to pihole
      FTLCONF_dns_upstreams: unbound
    ports:
      - "53:53/tcp" # DNS resolution
      - "53:53/udp" # DNS resolution
      - "853:853/tcp" # DNS over TLS
      # - "8081:80/tcp"  # Web interface managed by Caddy
    volumes:
      - "${PROJECT_PATH}/${CONFIG}/pihole/etc-pihole:/etc/pihole"
      - "${PROJECT_PATH}/${CONFIG}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "${PROJECT_PATH}/${CONFIG}/pihole/etc-lighttpd/external.conf:/etc/lighttpd/external.conf"
    networks:
      proxy-net:
        ipv4_address: "${PIHOLE_STATIC_IP}"
      private-net:
    restart: unless-stopped
    depends_on:
      - unbound