services:
  # Enable CacheDB Module with Redis backend
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - unbound-net
  
  unbound:
    container_name: unbound
    image: "klutchell/unbound:latest"
    networks:
      unbound-net:
        ipv4_address: "${UNBOUND_STATIC_IP}"
    volumes:
      - "${DOCKER_CONFIG_PATH}/unbound:/etc/unbound/custom.conf.d:ro"
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis: