services:
  unbound:
    container_name: unbound
    image: "klutchell/unbound:latest"
    networks:
      - unbound-net
#    volumes:
#      - "${DOCKER_CONFIG_PATH}/unbound:/etc/unbound/custom.conf.d"
    restart: unless-stopped