services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      # Tell Homeassistant configuration.yaml to allow proxy traffic
      PROXY_NET_SUBNET: "${PROXY_NET_SUBNET}"
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/homeassistant:/config
      - /run/dbus:/run/dbus:ro  # Bluetooth integration
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - proxy-net
      - private-net

  nodered:  # Port 1880
    # Low-code interface for automation
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    networks:
      - proxy-net
      - private-net
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "${TZ}"

  mosquitto:
    # MQTT broker
    # See: https://www.espboards.dev/blog/secure-mqtt-broker-docker-hass/
    # Runs with user 1883:1883
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - private-net
    #ports:
    #  - 1883:1883
    #  - 1884:1884
    #  - 9001:9001  # Websockets
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/mosquitto/config:/mosquitto/config
      - ${PROJECT_PATH}/${CONFIG}/mosquitto/data:/mosquitto/data
      - ${PROJECT_PATH}/${CONFIG}/mosquitto/log:/mosquitto/log
      - ${PROJECT_PATH}/certs/server:/certs
    environment:
      TZ: "${TZ}"

  zigbee2mqtt:  # Port 8080
  # https://www.zigbee2mqtt.io/guide/installation/02_docker.html
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      restart: unless-stopped
      group_add:
        - dialout  # Ensure has permissions for the adapter i.e.: ls -l /dev/ttyACM0
      user: 1000:1000
      volumes:
          - ${PROJECT_PATH}/${CONFIG}/zigbee2mqtt:/app/data
          - ${PROJECT_PATH}/certs/clients/zigbee2mqtt:/certs
          - /run/udev:/run/udev:ro
      #ports:
          # Frontend port
      #    - 8080:8080
      networks:
        - proxy-net
        - private-net
      environment:
          - TZ=${TZ}
      depends_on:
        - mosquitto
      devices:
          # Make sure this matched your adapter location
          # https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html#basic-configuration
          - ${ZIGBEE_ADAPTER_PORT}:/dev/ttyACM0