services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      # Tell Homeassistant configuration.yaml to allow proxy traffic
      PROXY_NET_SUBNET: "${PROXY_NET_SUBNET}"
    volumes:
      - ${DOCKER_CONFIG_PATH}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - proxy-net