services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    network_mode: host
    environment:
      # Tell Homeassistant configuration.yaml to allow proxy traffic
      PROXY_NET_SUBNET: "${PROXY_NET_SUBNET}"
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/homeassistant:/config
      - /run/dbus:/run/dbus:ro  # Bluetooth integration
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - proxy-net