services:
  caddy:
    image: caddy:latest
    container_name: caddy
    env_file:
      - "${PROJECT_PATH}/${CONFIG}/caddy/secrets/.hashes"
      - "${PROJECT_PATH}/${CONFIG}/caddy/secrets/.tokens"
    environment:  # Pass variables from the base compose
      CADDY_EMAIL: "${CADDY_EMAIL}"
      CADDY_LOGIN_TIMEOUT: "${CADDY_LOGIN_TIMEOUT}"
      DOMAIN: "${DOMAIN}"
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    networks:
      - proxy-net
    dns:
      - ${PIHOLE_STATIC_IP}   # Pi-hole on proxy-net
      - 1.1.1.1               # fallback so ACME works even if Pi-hole is down
      - 8.8.8.8
    depends_on:
      - pihole                 # ensure DNS is up before Caddy starts
    volumes:
      - "${PROJECT_PATH}/${CADDYFILE}:/etc/caddy/Caddyfile:ro"
      - "${PROJECT_PATH}/${CONFIG}/caddy/caddy_data:/data"
      - "${PROJECT_PATH}/${CONFIG}/caddy/caddy_config:/config"
    restart: unless-stopped