services:
  github-runner:
    container_name: github-runner
    image: uppertoe/pi-github-runner:latest
    restart: unless-stopped
    environment:
      GH_RUNNER_REPO: "${GH_RUNNER_REPO}"
      GH_RUNNER_CONFIG_TOKEN: "${GH_RUNNER_CONFIG_TOKEN}"
    volumes:
      - ${DOCKER_CONFIG_PATH}/github-runner:/home/github/actions-runner