# https://github.com/pawelmalak/flame
services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    environment:
      PASSWORD: "${FLAME_PASSWORD}"
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    restart: unless-stopped
    networks:
      - proxy-net