services:
  timetagger:
    container_name: timetagger
    restart: unless-stopped
    image: ghcr.io/almarklein/timetagger
    volumes:
      - ${PROJECT_PATH}/${CONFIG}/timetagger:/opt/_timetagger
    networks:
      - proxy-net